import {CalenderDaySelect, CheckSelect, PickerSelect, RadioSelect} from './helpers';

export default function (spec){
    spec.describe('One way purchase', function (){
        spec.it('process', async  function (){
            await spec.press("PtoPSearch.Exchange")
            await spec.pause(1000)
            await spec.press("PtoPSearch.Start.DateSelect")
            const Calender = await spec.findComponent("DateSelect")
            await CalenderDaySelect(Calender, {"dateString": "2021-07-28", "day": 28, "month": 7, "timestamp": 1627430400000, "year": 2021})
            await spec.press("PtoPSearch.confirm")
            await spec.pause(10000)
            await spec.press("RailInfoList.TimeSort")
            await spec.pause(2000)
            await spec.press("OneWay.RailwayCard1")
            await spec.pause(15000)
            await spec.press("PassengerSelect")
            await spec.pause(1000)
            // await spec.press("PassengerAdd")
            // await spec.fillIn("PassengerAdd.Username", "任浩天")
            // const picker1 = await spec.findComponent("PassengerAdd.P_type")
            // await PickerSelect(picker1, [0])
            // const picker2 = await spec.findComponent("PassengerAdd.C_type")
            // await PickerSelect(picker2, ["二代身份证"])
            // await spec.fillIn("PassengerAdd.Card_id", "410181200101258796")
            // await spec.fillIn("PassengerAdd.Tel_number", "13838167788")
            // await spec.press("PassengerAdd.confirm")
            await spec.pause(4000)
            const passenger0 = await spec.findComponent("Passenger0")
            await CheckSelect(passenger0)
            await spec.pause(3000)
            const passenger1 = await spec.findComponent("Passenger1")
            await CheckSelect(passenger1)
            await spec.pause(3000)
            const passenger2 = await spec.findComponent("Passenger2")
            await CheckSelect(passenger2)
            await spec.pause(3000)
            const passenger3 = await spec.findComponent("Passenger3")
            await CheckSelect(passenger3)
            await spec.pause(3000)
            await spec.press("PassengerSelect.confirm")
            await spec.pause(2000)
            await spec.press("PassengerSelect")
            await spec.pause(3000)
            await CheckSelect(passenger0)
            await spec.pause(3000)
            await spec.press("PassengerSelect.confirm")
            await spec.pause(2000)
            await spec.press("delete2")
            await spec.pause(1000)
            const Radio1 = await spec.findComponent("HighRail.Seat")
            await RadioSelect(Radio1, 0, 2)
            await spec.pause(1000)
            await RadioSelect(Radio1, 1, 2)
            await spec.pause(1000)
            await spec.press("OneWay.purchase")
            await spec.press("PayResult.confirm")
            await spec.press("Tab.Order")
        })
    })
}
