import {InputBlur, PickerSelect} from './helpers';

export default function (spec){
    spec.describe('Register', function (){
        spec.it(' successfully', async function () {
            await spec.press('Tab.User')
            await spec.press('Tab.User.UserInfo')
            await spec.press("Register")
            await spec.fillIn("Register.Username", "rht")
            const username = await spec.findComponent('Register.Username')
            await InputBlur(username)
            await spec.pause(1000)
            await spec.fillIn("Register.Username", "re")
            await InputBlur(username)
            await spec.pause(1000)
            await spec.fillIn("Register.Password", "Rht!123")
            await spec.fillIn("Register.Password2", "Rht!12")
            const password2 = await spec.findComponent('Register.Password2')
            await InputBlur(password2)
            await spec.pause(1000)
            await spec.fillIn("Register.Password2", "Rht!123")
            await InputBlur(password2)
            await spec.pause(1000)
            const picker1 = await spec.findComponent("Register.Card_type")
            await PickerSelect(picker1, ["中国居民身份证"])
            await spec.fillIn("Register.Real_name", "任浩天")
            await spec.fillIn("Register.Card_id", "141255125")
            const card_id = await spec.findComponent('Register.Card_id')
            await InputBlur(card_id)
            await spec.pause(1000)
            await spec.fillIn("Register.Card_id", "410181200101258796")
            await InputBlur(card_id)
            await spec.pause(1000)
            const tel_number = await spec.findComponent("Register.tel_number")
            await spec.fillIn("Register.tel_number", "13231332")
            await InputBlur(tel_number)
            await spec.pause(1000)
            await spec.fillIn("Register.tel_number", "13838167788")
            await InputBlur(tel_number)
            await spec.pause(1000)
            const e_mail = await spec.findComponent("Register.E_mail")
            await spec.fillIn("Register.E_mail", "13231332")
            await InputBlur(e_mail)
            await spec.pause(1000)
            await spec.fillIn("Register.E_mail", "1191602443@qq.com")
            await InputBlur(e_mail)
            await spec.pause(1000)
            const picker2 = await spec.findComponent("Register.Tourist_type")
            await PickerSelect(picker2, [1])
            await spec.press("Register.confirm")
            await spec.fillIn("Login.Username", "re")
            await spec.fillIn("Login.Password", "Rht!123")
            await spec.press('Login.confirm')
            await spec.pause(1000)
            await spec.notExists("UserInfo.LoginModal")
        })
    })
}
